module.exports = {
  privGroups: [
    {
      id: "Dashboard",
      name: "Dashboard Permissions",
    },
    {
      id: "User",
      name: "User Permissions",
    },
    {
      id: "Role",
      name: "Role Permissions",
    },
    {
      id: "Category",
      name: "Category Permissions",
    },
    {
      id: "AuditLogs",
      name: "AuditLogs Permissions",
    },
  ],
  Privileges: [
    {
      Key: "dashboard_view",
      Name: "View",
      Group: "Dashboard",
      Description: "Dashboard Permissions",
      type: "system",
    },
    {
      Key: "user_view",
      Name: "View",
      Group: "User",
      Description: "User Permissions",
      type: "system",
    },
    {
      Key: "user_add",
      Name: "Add",
      Group: "User",
      Description: "User Permissions",
      type: "system",
      dependencies: { and: ["user_view", "role_view"] },
    },
    {
      Key: "user_update",
      Name: "Update",
      Group: "User",
      Description: "User Permissions",
      type: "system",
      dependencies: { and: ["user_view", "role_view"] },
    },
    {
      Key: "user_delete",
      Name: "Delete",
      Group: "User",
      Description: "User Permissions",
      type: "system",
      dependencies: { and: ["user_view"] },
    },
    {
      Key: "role_view",
      Name: "View",
      Group: "Role",
      Description: "Role Permissions",
      type: "system",
    },
    {
      Key: "role_add",
      Name: "Add",
      Group: "Role",
      Description: "Role Permissions",
      type: "system",
      dependencies: { and: ["role_view"] },
    },
    {
      Key: "role_update",
      Name: "Update",
      Group: "Role",
      Description: "Role Permissions",
      type: "system",
      dependencies: { and: ["role_view"] },
    },
    {
      Key: "role_delete",
      Name: "Delete",
      Group: "Role",
      Description: "Role Permissions",
      type: "system",
      dependencies: { and: ["role_view"] },
    },
    {
      Key: "category_view",
      Name: "View",
      Group: "Category",
      Description: "Category Permissions",
      type: "system",
    },
    {
      Key: "category_add",
      Name: "Add",
      Group: "Category",
      Description: "Category Permissions",
      type: "system",
      dependencies: { and: ["category_view"] },
    },
    {
      Key: "category_update",
      Name: "Update",
      Group: "Category",
      Description: "Category Permissions",
      type: "system",
      dependencies: { and: ["category_view"] },
    },
    {
      Key: "category_delete",
      Name: "Delete",
      Group: "Category",
      Description: "Category Permissions",
      type: "system",
      dependencies: { and: ["category_view"] },
    },
    {
      Key: "auditlog_view",
      Name: "View",
      Group: "AuditLogs",
      Description: "AuditLogs Permissions",
      type: "system",
    },
  ],
};
